# Generated by Django 2.2.7 on 2019-12-04 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostGroupSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Shared Time')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(blank=True)),
                ('postedOn', models.DateTimeField(default=datetime.datetime.now, verbose_name='Posted Time')),
                ('editedOn', models.DateTimeField(auto_now=True, verbose_name='Last Edited Time')),
                ('coverPic', models.ImageField(blank=True, upload_to='coverpics')),
            ],
        ),
        migrations.CreateModel(
            name='PostUserSharing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Shared Time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='posts.Posts')),
            ],
        ),
    ]
