# Generated by Django 2.2.7 on 2019-11-30 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupId', models.AutoField(primary_key=True, serialize=False, verbose_name='Group ID')),
                ('groupName', models.CharField(max_length=50, verbose_name='Group Name')),
                ('creationDate', models.DateField(default=datetime.datetime.now, verbose_name='Group Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOfJoining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, verbose_name='Joining Time')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_joining_time', to='groups.Groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_joining_time', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
