# Generated by Django 2.2.7 on 2019-11-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20191130_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='groupId',
        ),
        migrations.AddField(
            model_name='groups',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeofjoining',
            name='isAdmin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
