# Generated by Django 2.2.7 on 2019-11-30 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191130_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeofjoining',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='groups.Groups'),
        ),
        migrations.AlterField(
            model_name='timeofjoining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
